# -*- coding: utf-8 -*-
"""Crop_yield.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPDnMnbVCpagRBQqd_2DdLMxmykiVhmJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.image as mpimg
from sklearn.preprocessing import LabelEncoder as labelencoder

crop=pd.read_csv('crop_yield.csv')

crop=crop.drop(['Crop_Year'],axis=1)

crop.head(5)

crop.Crop.value_counts().sum()

crop.isnull().sum()

crop.dtypes

crop['Season']=crop['Season'].astype('string')

crop['Crop']=crop['Crop'].astype('string')

crop.dtypes

le = labelencoder()
crop['Crop'] = le.fit_transform(crop['Crop'])

lo=labelencoder()
crop['State']=lo.fit_transform(crop['State'])

lp=labelencoder()
crop['Season']=lp.fit_transform(crop['Season'])

crop.duplicated().sum()

x=crop.drop(['Yield'],axis=1)
y=crop['Yield']

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

crop.shape

from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsRegressor()

model.fit(X_train,y_train)

k=model.predict(X_train)
model.score(X_train,y_train)

crop.dtypes

input_data = ['Coconut', 'Whole Year','Assam', 19656.0, 126905000, 2051.4, 1870661.52,6093.36]
feature=[	'Crop',	'Season','State'	,'Area',	'Production',	'Annual_Rainfall',	'Fertilizer',	'Pesticide']

input_data[0] = le.fit_transform([input_data[0]])[0]
input_data[1] = lp.fit_transform([input_data[1]])[0]
input_data[2] = lo.fit_transform([input_data[2]])[0]
df=pd.DataFrame([input_data],columns=feature)
p = np.array(input_data)
p = p.reshape(1, -1)

output = model.predict(df)
print(output)

crop.head(5)